### PR TITLE
added angular code snippets in style guide

### PR DESCRIPTION
**Pull request by osvaldoFernandez92**
Added angular snippets section in angular section

### CODE REVIEW

**Comment by mishuagopian** [comment]
@SKOLZ @osvaldoFernandez92 ping here!

**Comment by mvbattan** [comment]
@mishuagopian Ping here !

**Comment by osvaldoFernandez92** [comment]
we need something to close this since its approved

**Comment by mvbattan** [comment]
@osvaldoFernandez92 Remember to unassign yourself once you've finished doing requested changes. Also assign this to those people with merge permissions if this is able to merge :smile:

**Pull request merged**
